// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: RobotContainer.

#pragma once

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include <frc/smartdashboard/SendableChooser.h>
#include <frc2/command/Command.h>

#include "subsystems/Drivetrain.h"

#include "commands/AutonomousCommand.h"
#include "commands/LineAlignCommand.h"

#include <frc/XboxController.h>
#include <frc2/command/button/JoystickButton.h>

#include "Constants.h"


// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

class RobotContainer {

public:

    frc2::Command* GetAutonomousCommand();
    static RobotContainer* GetInstance();

// The robot's subsystems
Drivetrain   m_drivetrain;


frc::XboxController* getXboxDriveController();
frc::XboxController* getXboxMechanismController();

private:

    RobotContainer();

// Joysticks
    frc::XboxController m_xboxDriveController{Porterbots::Controller::kDriveController};
    frc::XboxController m_xboxMechanismController{Porterbots::Controller::kMechanismController};

    frc::SendableChooser<frc2::Command*> m_chooser;

    AutonomousCommand m_autonomousCommand;
    //LineAlignCommand  m_lineAlignCommand;

    static RobotContainer* m_robotContainer;

    void ConfigureButtonBindings();
};