// AutonomousCommand.h

#pragma once

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

#include <frc2/command/CommandHelper.h>
#include <frc2/command/CommandBase.h>

#include "subsystems/Drivetrain.h"


/**
 *
 *
 * @author Lockport Porterbots
 */
class AutonomousCommand: public frc2::CommandHelper<frc2::CommandBase, AutonomousCommand> {
public:
    explicit AutonomousCommand(Drivetrain&);

    void Initialize() override;
    void Execute() override;
    bool IsFinished() override;
    void End(bool interrupted) override;
    bool RunsWhenDisabled() const override;


private:

    Drivetrain* m_drivetrain;
};
