// MoveMotor.h

#pragma once

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

#include <frc2/command/CommandHelper.h>
#include <frc2/command/CommandBase.h>

#include "subsystems/Drivetrain.h"


/**
 *
 *
 * @author Lockport Porterbots
 */
class MoveMotor: public frc2::CommandHelper<frc2::CommandBase, MoveMotor> {
public:
    explicit MoveMotor();

    void Initialize() override;
    void Execute() override;
    bool IsFinished() override;
    void End(bool interrupted) override;
    bool RunsWhenDisabled() const override;


private:
    WPI_VictorSPX m_motor{14};
    frc::MotorControllerGroup m_motorController{m_motor};    
    
};
