// MoveMotor

#include "commands/MoveMotor.h"

MoveMotor::MoveMotor() {

    // Use AddRequirements() here to declare subsystem dependencies
    // eg. AddRequirements(m_Subsystem);
    SetName("MoveMotor");

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

}

// Called just before this Command runs the first time
void MoveMotor::Initialize() {
    //m_drivetrain->TankDrive(0.05,0.05,false);
}

// Called repeatedly when this Command is scheduled to run
void MoveMotor::Execute() {
    m_motorController.Set(0.1);
}

// Make this return true when this Command no longer needs to run execute()
bool MoveMotor::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void MoveMotor::End(bool interrupted) {
    m_motorController.Set(0);
}

bool MoveMotor::RunsWhenDisabled() const {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    return false;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
}
