// AutonomousCommand

#include "commands/MovingSolenoidBasic.h"

MovingSolenoidBasic::MovingSolenoidBasic(Drivetrain& ) : (&drivetrain) {

    // Use AddRequirements() here to declare subsystem dependencies
    // eg. AddRequirements(m_Subsystem);
    SetName("AutonomousCommand");

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

}

// Called just before this Command runs the first time
void MovingSolenoidBasic::Initialize() {
}

// Called repeatedly when this Command is scheduled to run
void MovingSolenoidBasic::Execute() {
}

// Make this return true when this Command no longer needs to run execute()
bool MovingSolenoidBasic::IsFinished() {
    return false;
}

// Called once after isFinished returns true
}

bool MovingSolenoidBasic::RunsWhenDisabled() const {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    return false;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
}
